#SPDX-License-Identifier: MIT-0
---
# tasks file for ansible/roles/nfs-client

- name: Set runtime hostname
  ansible.builtin.command: hostname {{ hostname }}

- name: Persist hostname in rc.conf
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    regexp: "^hostname="
    line: 'hostname="{{ hostname }}"'
    create: yes

# - name: Set hostname with sysrc
#   ansible.builtin.command: sysrc hostname={{ hostname }}

# - name: Apply hostname immediately
#   ansible.builtin.command: hostname {{ hostname }}

- name: Install packages
  community.general.pkgng:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: Allow wheel group sudo without password
  ansible.builtin.lineinfile:
    path: /usr/local/etc/sudoers
    regexp: '^# %wheel ALL=\(ALL\) ALL'
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/local/sbin/visudo -cf %s"

- name: Add existing users to wheel group
  ansible.builtin.user:
    name: spike
    groups: wheel
    append: true

- name: Add group
  ansible.builtin.group:
    name: crew
    state: present

- name: Create user
  user:
    name: "{{ item }}"
    shell: /bin/tcsh
    state: present
    password: "{{ 'valentine' | password_hash('sha512') }}"
  loop: "{{ accounts }}"

- name: Add user
  ansible.builtin.user:
    name: "{{ item }}"
    comment: "{{ item }}"
    groups: wheel, crew
    state: present
  loop: "{{ accounts }}"

- name: Create directory
  file:
    path: "/mnt/nfs/{{ item }}"
    owner: "{{ item }}"
    group: "{{ item }}"
    state: directory
  loop: "{{ accounts }}"

- name: Mount directories
  ansible.posix.mount:
    src: "{{ nfs }}:/nfs/{{ item }}"
    path: "/mnt/nfs/{{ item }}"
    state: mounted
    fstype: nfs
    opts: rw
  loop: "{{ accounts }}"

- name: Enable nfs at boot
  community.general.sysrc:
    name: nfs_client_enable
    value: "YES"

- name: Update tcsh prompt
  ansible.builtin.replace:
    path: "/home/{{ item }}/.cshrc"
    regexp: '^\t*set\s+prompt\s*=.*'
    replace: '\tset prompt="\\n%{\033[0;32m%}%n@%m:%{\033[0;33m%}%~%{\033[1;30m%}>%{\033[1;37m%} "'
    owner: "{{ item }}"
    group: "{{ item }}"
  loop: "{{ accounts }}"

- name: Ensure emacs directory exists
  ansible.builtin.file:
    path: "/home/{{ item }}/.emacs.d"
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: "0755"
  loop: "{{ accounts }}"

- name: Copy init.el
  ansible.builtin.template:
    src: init-v5.el.j2
    dest: "/home/{{ item }}/.emacs.d/init.el"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: "0644"
  loop: "{{ accounts }}"
