#SPDX-License-Identifier: MIT-0
---
# tasks file for ansible/roles/bastille
- name: Set runtime hostname
  ansible.builtin.command: hostname {{ hostname }}

- name: Persist hostname in rc.conf
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    regexp: "^hostname="
    line: 'hostname="{{ hostname }}"'
    create: yes

- name: Install packages
  community.general.pkgng:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: Enable bastille at boot
  community.general.sysrc:
    name: bastille_enable
    value: "YES"

- name: Clone interface
  ansible.builtin.shell: /usr/sbin/sysrc cloned_interfaces+=lo1

- name: Name interface
  community.general.sysrc:
    name: ifconfig_lo1_name
    value: "bastille0"

- name: Start service
  ansible.builtin.shell: /usr/sbin/service netif cloneup
  register: result_service

- name: Bootstrap Bastille release
  command: bastille bootstrap {{ bastille_release }}
  args:
    creates: "/usr/local/bastille/releases/{{ bastille_release }}"

- name: Create jail
  ansible.builtin.shell: "bastille create {{ item.name }} {{ bastille_release }}  {{prefix}}.{{ item.octet }}/24 {{ ext_if }}"
  with_items: "{{ jails }}"
  args:
    creates: "/usr/local/bastille/jails/{{ item.name }}"
  # notify: reload pf

- name: Add proxy pkg
  ansible.builtin.blockinfile:
    path: /usr/local/etc/pkg.conf
    block: |
      PKG_ENV: {
        HTTP_PROXY  : "{{ http_proxy }}"
        HTTPS_PROXY : "{{ https_proxy }}"
      }
    append_newline: true
    prepend_newline: true

- name: Create directory pk
  file:
    path: "/usr/local/bastille/jails/{{ item.name }}/root/usr/local/etc"
    state: directory
    recurse: yes
  loop: "{{ jails }}"

- name: Add proxy pkg
  ansible.builtin.blockinfile:
    path: "/usr/local/bastille/jails/{{ item.name }}/root/usr/local/etc/pkg.conf"
    block: |
      PKG_ENV: {
        HTTP_PROXY  : "{{ http_proxy }}"
        HTTPS_PROXY : "{{ https_proxy }}"
      }
    create: true
  loop: "{{ jails }}"

- name: Update jail
  ansible.builtin.shell: "bastille cmd {{ item.name }} env ASSUME_ALWAYS_YES=yes pkg update "
  with_items: "{{ jails }}"

- name: Add packages
  ansible.builtin.shell: "bastille pkg {{ item.0.name }} install -y {{ item.1 }}"
  loop: "{{ jails|subelements('packages') }}"

- name: Deploy pf.conf
  template:
    src: pf.conf.j2
    dest: /etc/pf.conf
    owner: root
    group: wheel
    mode: "0644"

- name: Check if pf module is loaded
  command: kldstat -n pf
  register: pf_loaded
  failed_when: false
  changed_when: false

- name: Load pf module if not loaded
  command: kldload pf
  when: pf_loaded.rc != 0

- name: check pf.conf
  command: pfctl -vnf /etc/pf.conf
  register: pf_check
  changed_when: false

- name: reload pf
  command: pfctl -f /etc/pf.conf
  when: pf_check.rc == 0
  notify: reload pf
