#SPDX-License-Identifier: MIT-0
---
# tasks file for ansible/roles/storage
- name: Set runtime hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Persist hostname in rc.conf
  community.general.sysrc:
    name: hostname
    value: "{{ hostname }}"

- name: Install host packages
  community.general.pkgng:
    name: "{{ packages }}"
    state: present

- name: Enable bastille at boot
  community.general.sysrc:
    name: bastille_enable
    value: "YES"

- name: Configure Bastille loopback clone
  community.general.sysrc:
    name: cloned_interfaces
    value: lo1

- name: Rename lo1 to bastille0
  community.general.sysrc:
    name: ifconfig_lo1_name
    value: bastille0

- name: Bring cloned interfaces up
  ansible.builtin.command: service netif cloneup
  changed_when: false

- name: Bootstrap Bastille release
  ansible.builtin.command: "bastille bootstrap {{ bastille_release }}"
  args:
    creates: "/usr/local/bastille/releases/{{ bastille_release }}"

######################################
# PF CONFIGURATION
######################################

- name: Deploy pf.conf
  ansible.builtin.template:
    src: pf.conf.j2
    dest: /etc/pf.conf
    owner: root
    group: wheel
    mode: "0644"
  tags: pfconf

# - name: Ensure pf kernel module is loaded
#   ansible.builtin.command: kldload pf
#   register: pf_kldload
#   failed_when: pf_kldload.rc != 0 and 'File exists' not in pf_kldload.stderr
#   changed_when: pf_kldload.rc == 0

- name: Check if pf kernel module is loaded
  ansible.builtin.command: kldstat -n pf
  register: pf_loaded
  failed_when: false
  changed_when: false

- name: Load pf kernel module
  ansible.builtin.command: kldload pf
  when: pf_loaded.rc != 0

- name: Enable pf at boot
  community.general.sysrc:
    name: pf_enable
    value: "YES"

- name: Validate pf.conf
  ansible.builtin.command: pfctl -vnf /etc/pf.conf
  register: pf_check
  changed_when: false
  failed_when: pf_check.rc != 0

- name: Reload pf if valid
  command: pfctl -f /etc/pf.conf
  when: pf_check.rc == 0
  notify: reload pf

###################################################
# CREATE JAILS
###################################################

- name: Create jails
  ansible.builtin.command: >-
    bastille create {{ item.name }} {{ bastille_release }}
    {{ item.prefix }}.{{ item.octet }} {{ bastille_interface }}
  loop: "{{ jails }}"
  args:
    creates: "/usr/local/bastille/jails/{{ item.name }}"

- name: Copy host resolv.conf into jails
  ansible.builtin.copy:
    src: /etc/resolv.conf
    dest: "/usr/local/bastille/jails/{{ item.name }}/root/etc/resolv.conf"
    remote_src: true
    owner: root
    group: wheel
    mode: "0644"
  loop: "{{ jails }}"

- name: Configure host pkg proxy
  ansible.builtin.blockinfile:
    path: /usr/local/etc/pkg.conf
    create: true
    marker: "# {mark} ANSIBLE MANAGED PKG PROXY"
    block: |
      PKG_ENV: {
        HTTP_PROXY  : "{{ http_proxy }}"
        HTTPS_PROXY : "{{ https_proxy }}"
      }
  when: http_proxy is defined or https_proxy is defined

- name: Ensure jail pkg configuration directory exists
  ansible.builtin.file:
    path: "/usr/local/bastille/jails/{{ item.name }}/root/usr/local/etc"
    state: directory
    owner: root
    group: wheel
    mode: "0755"
  loop: "{{ jails }}"

- name: Configure jail pkg proxy
  ansible.builtin.blockinfile:
    path: "/usr/local/bastille/jails/{{ item.name }}/root/usr/local/etc/pkg.conf"
    create: true
    marker: "# {mark} ANSIBLE MANAGED PKG PROXY"
    block: |
      PKG_ENV: {
        HTTP_PROXY  : "{{ http_proxy }}"
        HTTPS_PROXY : "{{ https_proxy }}"
      }
  loop: "{{ jails }}"
  when: http_proxy is defined or https_proxy is defined

- name: Update pkg catalog in jails
  ansible.builtin.command: "bastille cmd {{ item.name }} env ASSUME_ALWAYS_YES=yes pkg update"
  loop: "{{ jails }}"
  # changed_when: false
  changed_when: "'No updates' not in jail_pkg_update.stdout"
  register: jail_pkg_update
  failed_when: jail_pkg_update.rc != 0

######################################
# DAEMON CONFIGURATION
######################################

- name: Install packages in jails
  ansible.builtin.command: "bastille pkg {{ item.0.name }} install -y {{ item.1 }}"
  loop: "{{ jails | subelements('packages', skip_missing=True) }}"
  register: jail_pkg_install
  changed_when: "'already installed' not in jail_pkg_install.stdout"

- name: Enable daemons in jails
  ansible.builtin.command: "bastille sysrc {{ item.0.name }} {{ item.1 }}_enable=YES"
  loop: "{{ jails | subelements('daemons', skip_missing=True) }}"

######################################
# NATS CONFIGURATION
######################################

- name: Get nats jail
  set_fact:
    nats_jail: "{{ jails | selectattr('name', 'equalto', 'nats-server') | first }}"

- name: Deploy nats-server
  template:
    src: nats-server.j2
    dest: "/usr/local/bastille/jails/{{ nats_jail.name }}/root/usr/local/etc/nats-server"
    owner: root
    group: wheel
    mode: "0644"
  when: nats_jail is defined

- name: Restart services in jails
  ansible.builtin.command: >
    bastille service {{ nats_jail.name }} {{ item }} restart
  loop: "{{ nats_jail.services }}"

######################################
# NFS CONFIGURATION PERMISSIONS
######################################

- name: Get nfs jail
  set_fact:
    nfs_jail: "{{ jails | selectattr('name', 'equalto', 'nfs-server') | first }}"

- name: Check if group exists in jail
  command: >
    bastille cmd {{ item.0.name }} pw groupshow {{ item.1.name }}
  register: jail_group_check
  failed_when: false
  changed_when: false
  loop: "{{ jails | subelements('new_groups', skip_missing=True) }}"

- name: Add groups in jail
  command: >
    bastille cmd {{ item.item.0.name }} pw groupadd -n {{ item.item.1.name }} -g {{ item.item.1.gid }}
  loop: "{{ jail_group_check.results }}"
  when: item.rc != 0

- name: Check if user exists in jail
  command: >
    bastille cmd {{ item.0.name }} pw usershow {{ item.1.name }}
  register: jail_user_check
  failed_when: false
  changed_when: false
  loop: "{{ jails | subelements('accounts', skip_missing=True) }}"

- name: Add users in jail
  command: >
    bastille cmd {{ item.item.0.name }} pw useradd -n {{ item.item.1.name }}
    -u {{ item.item.1.uid }}
    -g {{ item.item.1.gid }}
    -G wheel
    -c "{{ item.item.1.name }}"
    -m
    -s /bin/tcsh
  loop: "{{ jail_user_check.results }}"
  when: item.rc != 0

- name: Create home directories in jail rootfs
  file:
    path: "/usr/local/bastille/jails/{{ item.0.name }}/root/home/{{ item.1.name }}"
    owner: "{{ item.1.uid }}"
    group: "{{ item.1.gid }}"
    mode: "0700"
    state: directory
  loop: "{{ jails | subelements('accounts', skip_missing=True) }}"

- name: Create source NFS directories in jail rootfs
  ansible.builtin.file:
    path: "/usr/local/bastille/jails/{{ nfs_jail.name }}/root/nfs/{{ item.name }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  loop: "{{ nfs_exports }}"
  when: nfs_jail is defined

- name: Create nullfs mount points on host
  ansible.builtin.file:
    path: "/srv/nfs/{{ item.name }}"
    owner: 0
    group: 0
    mode: "0755"
    state: directory
  loop: "{{ nfs_exports }}"
  when: nfs_jail is defined

- name: Mount nullfs exports
  ansible.posix.mount:
    src: "/usr/local/bastille/jails/{{ nfs_jail.name }}/root/nfs/{{ item.name }}"
    path: "/srv/nfs/{{ item.name }}"
    fstype: nullfs
    opts: rw
    state: mounted
  loop: "{{ nfs_exports }}"
  when: nfs_jail is defined

- name: Deploy exports
  template:
    src: exports.j2
    dest: "/etc/exports"
    owner: root
    group: wheel
    mode: "0644"

- name: Restart services in jails
  ansible.builtin.command: >
    bastille service {{ item.0.name }} {{ item.1 }} restart
  loop: "{{ jails | subelements('services', skip_missing=True) }}"
  loop_control:
    label: "[{{ item.0.name }}] {{ item.1 }}"

######################################
# DAEMON CONFIGURATION
######################################

- name: Enable nfs at boot
  community.general.sysrc:
    name: nfs_server_enable
    value: "YES"

- name: Tune nfsd threads
  community.general.sysrc:
    name: nfs_server_flags
    value: "-u -t 8"

- name: Enable mount at boot
  community.general.sysrc:
    name: mountd_enable
    value: "YES"

- name: Allow non-reserved ports for mountd
  community.general.sysrc:
    name: mountd_flags
    value: "-n"

- name: Enable rpcbind at boot
  community.general.sysrc:
    name: rpcbind_enable
    value: "YES"

- name: Disable NFSv4 (optional but cleaner)
  community.general.sysrc:
    name: nfsv4_server_enable
    value: "NO"

- name: Allow non-reserved ports for nfsd
  ansible.posix.sysctl:
    name: vfs.nfsd.nfs_privport
    value: "0"
    state: present

######################################
# RESTART DAEMONS
######################################

- name: Ensure service are running
  ansible.builtin.shell: >
    service {{ item }} restart
  loop:
    - rpcbind
    - nfsd
    - mountd

######################################
# PF CONFIGURATION
######################################

- name: Configure tcsh prompt
  ansible.builtin.lineinfile:
    path: "/usr/local/bastille/jails/{{ item.0.name }}/root/home/{{ item.1.name }}/.cshrc"
    regexp: '^\s*set\s+prompt\s*=.*'
    line: '	set prompt="%{\033[0m%}\n%{\033[0;32m%}%n@%m%{\033[0m%}:%{\033[0;33m%}%~%{\033[0m%} %# "'
    create: true
  loop: "{{ jails | subelements('accounts', skip_missing=True) }}"

- name: Update tcsh prompt
  ansible.builtin.replace:
    path: "/home/{{ item.1.name }}/.cshrc"
    regexp: '^\t*set\s+prompt\s*=.*'
    replace: '\tset prompt="\\n%{\033[0;32m%}%n@%m:%{\033[0;33m%}%~%{\033[1;30m%}>%{\033[1;37m%} "'
    owner: "{{ item.1.uid }}"
    group: "{{ item.1.gid }}"
  loop: "{{ jails | subelements('accounts', skip_missing=True) }}"
  tags: prompt

- name: Restart pf
  shell:
    cmd: >
      (( sleep 5; nohup service pf restart 1>/dev/null 2>&1 ) & )
