#SPDX-License-Identifier: MIT-0
---
# defaults file for ansible/roles/nfs-server

packages:
  - sudo
  - emacs-nox

# accounts:
# - spike
# - faye
accounts:
  - name: spike
    uid: 1001
    gid: 1010
  - name: faye
    uid: 1020
    gid: 1020

ext_if: "eth0"
