---
- name: install dev
  hosts: all
  become: true

  vars:
    nfs: "${nfs}"
    http_proxy: "${proxy}"
    https_proxy: "${proxy}"
    no_proxy: "${noproxy}"

  environment:
    http_proxy: "${proxy}"
    https_proxy: "${proxy}"
    no_proxy: "${noproxy}"

  roles:
    - roles/nfs-client
