#SPDX-License-Identifier: MIT-0
---
# tasks file for ansible/roles/quicklisp
- name: Install packages
  community.general.pkgng:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: Ensure quicklisp directory exists
  ansible.builtin.file:
    path: "/home/{{ item.name }}/quicklisp"
    state: directory
    owner: "{{ item.uid }}"
    group: "{{ item.gid }}"
    mode: "0755"
  loop: "{{ accounts }}"

- name: Download quicklisp bootstrap
  ansible.builtin.get_url:
    url: "{{ quicklisp_url }}"
    dest: "{{ quicklisp_bootstrap }}"
    mode: "0644"

- name: Install Quicklisp (SBCL) non-interactively
  ansible.builtin.command: >
    {{ lisp_cmd }}
    --noinform
    --non-interactive
    --load {{ quicklisp_bootstrap }}
    --eval '(quicklisp-quickstart:install :path "/home/{{ item.name }}/quicklisp")'
    --quit
  args:
    creates: "/home/{{ item.name }}/quicklisp/setup.lisp"
  loop: "{{ accounts }}"

- name: Change permission
  ansible.builtin.file:
    dest: "/home/{{ item.name }}/quicklisp"
    owner: "{{ item.uid }}"
    group: "{{ item.gid }}"
    recurse: yes
  loop: "{{ accounts }}"

- name: Ensure SBCL system rc exists
  ansible.builtin.file:
    path: "/home/{{ item.name }}/.sbclrc"
    state: touch
    owner: "{{ item.uid }}"
    group: "{{ item.gid }}"
    mode: "0644"
  loop: "{{ accounts }}"

- name: Add Quicklisp autoload to /etc/sbclrc
  ansible.builtin.blockinfile:
    path: "/home/{{ item.name }}/.sbclrc"
    marker: ";; {mark} ANSIBLE MANAGED QUICKLISP"
    block: |
      ;;; The following lines added by ql:add-to-init-file:
      #-quicklisp
      (let ((quicklisp-init (merge-pathnames "quicklisp/setup.lisp"
                                             (user-homedir-pathname))))
        (when (probe-file quicklisp-init)
           (load quicklisp-init)))

      (setf sb-impl::*default-external-format* :utf-8)
  loop: "{{ accounts }}"
