---
- name: install dev
  hosts: all
  become: true

  vars:
    prefix: "192.188.200.0"
    http_proxy: ""
    https_proxy: ""
    no_proxy: "192.188.200.0/24"

  environment:
    http_proxy: ""
    https_proxy: ""
    no_proxy: "192.188.200.0/24"

  roles:
    - roles/nfs-server
