#SPDX-License-Identifier: MIT-0
---
# defaults file for ansible/roles/nfs-client

packages:
  - sbcl
  - nfs-common

accounts:
  - name: spike
    uid: 1010
    gid: 1010
  # - name: faye
  #   uid: 1020
  #   gid: 1020

new_groups:
  - name: spike
    gid: 1010
  - name: faye
    gid: 1020
  - name: crew
    gid: 1030

# mount_path: /srv/nfs

account: spike spiegel
email: spike@gmail.com
